const cards = [
    {
      img: "../images/catalog1.jpg",
      title: "Сумка-Торба",
      price: 4200,
      order: 1,
      type: 0,
      code: 'lilmzk',
      desc: '123',
    },
    {
      img: "../images/catalog2.jpg",
      title: "Сумка с бахромой",
      price: 5200,
      order: 2,
      type: 0,
      code: 'nwmniy',
      desc: '123',
    },
    {
      img: "../images/catalog3.jpg",
      title: "Дорожка на стол",
      price: 2000,
      order: 3,
      type: 1,
      code: 'unlsni',
      desc: '123',
    },
    {
      img: "../images/catalog4.jpg",
      title: "Салфетница",
      price: 1500,
      order: 4,
      type: 1,
      code: 'ikipol',
      desc: '123',
    },
    {
      img: "../images/catalog5.jpg",
      title: "Сумка Таби",
      price: 3200,
      order: 5,
      type: 0,
      code: 'dhmyov',
      desc: '123',
    },
    {
      img: "../images/catalog6.jpg",
      title: "Сумка летняя Сансара",
      price: 5500,
      order: 6,
      type: 0,
      code: 'ntrgux',
      desc: '123',
    },
    {
      img: "../images/catalog7.jpg",
      title: "Сумка с рогаликами",
      price: 4200,
      order: 7,
      type: 0,
      code: 'dnknef',
      desc: '123',
    },
    {
      img: "../images/catalog8.jpg",
      title: "Кардхолдер",
      price: 500,
      order: 8,
      type: 1,
      code: 'bxausk',
      desc: '123',
    },
    {
      img: "../images/catalog9.jpg",
      title: "Бутылочница из джута",
      price: 1500,
      order: 9,
      type: 1,
      code: 'riftqc',
      desc: '123',
    },
    {
      img: "../images/catalog10.jpg",
      title: "Лежанка для питомцев",
      price: 3000,
      order: 10,
      type: 1,
      code: 'dsqjoq',
      desc: '123',
    },
    {
      img: "../images/catalog11.jpg",
      title: "Набор корзин «Свадебные»",
      price: 3000,
      order: 11,
      type: 1,
      code: 'nozdri',
      desc: '123',
    },
    {
      img: "../images/catalog12.jpg",
      title: "Корзина «Рыбка»",
      price: 1200,
      order: 12,
      type: 1,
      code: 'pxugvu',
      desc: '123',
    },
  ];